"""init database

Revision ID: 8b87d8c1306
Revises: None
Create Date: 2015-03-03 02:36:10.779782

"""

# revision identifiers, used by Alembic.
revision = '8b87d8c1306'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feeds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Unicode(length=200), nullable=True),
    sa.Column('url', sa.String(length=200), nullable=True),
    sa.Column('rss', sa.String(length=200), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('feeds_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author', sa.Unicode(length=200), nullable=True),
    sa.Column('feed_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.Unicode(length=200), nullable=True),
    sa.Column('link', sa.String(length=200), nullable=True),
    sa.Column('des', sa.Unicode(length=500), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('hits', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['feed_id'], ['feeds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('link')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feeds_item')
    op.drop_table('user')
    op.drop_table('feeds')
    ### end Alembic commands ###
